spring.application.name=Employee-Management-System
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_sys
spring.datasource.username=postgres
#spring.jpa.hibernate.ddl-auto=<create | create-drop | update | validate | none>
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.password=BEN102005
spring.jpa.properties.hibernate.format_sql=true
